# Bài 1 Tạo Tensor cơ bản

## Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.
### Yêu cầu: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

In [2]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

print("Kích thước:", a.shape)
print("Số chiều:", a.ndim)
print("Kiểu dữ liệu:", a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32


# Bài 2. Tạo các Tensor thường dùng

## Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

### Yêu cầu:
#### • Nhận xét sự khác nhau giữa torch.rand() và torch.randn().
#### • Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

In [4]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

f = torch.full((5, 5), 10)
print(f)

tensor([[0.8912, 0.1663, 0.3285, 0.3728],
        [0.8759, 0.7171, 0.8742, 0.2037],
        [0.1304, 0.1196, 0.3113, 0.2102]])
tensor([[ 0.0578, -0.0045, -0.5965, -0.0625],
        [-0.4487, -1.5536, -0.6849, -0.5370],
        [ 0.7807, -1.1938,  1.6450,  1.1429]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


# Bài 3. Kiểm tra thông tin Tensor

## Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

### Yêu cầu: Giải thích ý nghĩa của torch.Size([2, 3, 4]).

In [8]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


# Bài 4. Slicing và Indexing

## Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

### Yêu cầu:
#### • Cho biết shape của a[1] và a[1:, 2:4].
#### • Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

In [10]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

print("\nHai phần tử cuối cùng trên chiều thứ ba:")
print(a[:, :, -2:])

Original tensor:
tensor([[[-0.0620,  0.1980,  0.1351,  2.0901, -1.9470],
         [ 0.8933, -0.4798, -0.9315,  0.4309, -1.0977],
         [ 0.2404,  0.1006,  1.0696, -1.0478,  1.0921],
         [ 0.3013, -0.4351, -0.5622,  0.3549, -0.4580]],

        [[ 0.7408,  0.9922, -2.5362,  0.1379, -0.6987],
         [ 0.5795, -1.1075, -2.1476,  0.1030,  0.0838],
         [-0.9275, -0.0553, -0.0978,  1.0843,  0.0076],
         [ 0.5524, -0.9990, -0.9218,  0.7253, -0.4564]],

        [[-0.3814, -1.1657, -0.1675,  0.9360,  1.8601],
         [ 1.6559,  0.5931,  1.0621,  0.2320,  1.5918],
         [ 0.5564,  0.6336,  0.9935,  1.2389,  1.7096],
         [-0.2961,  0.6675, -1.3636,  0.0051,  0.5931]]])

Tensor a[1]:
tensor([[ 0.7408,  0.9922, -2.5362,  0.1379, -0.6987],
        [ 0.5795, -1.1075, -2.1476,  0.1030,  0.0838],
        [-0.9275, -0.0553, -0.0978,  1.0843,  0.0076],
        [ 0.5524, -0.9990, -0.9218,  0.7253, -0.4564]])

Tensor a[1:, 2:4]:
tensor([[[-0.9275, -0.0553, -0.0978,  1.0843,  0.0

# Bài 5. Reshape và Flatten

## Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

### Yêu cầu:
#### • Kiểm tra số phần tử trước và sau khi reshape.
#### • Thử reshape Tensor thành kích thước 2 × 6.

In [20]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

print("\nSo phan tu ban dau:", a.numel())
print("So phan tu sau reshape:", a.reshape(3, 2, 2).numel())

print("\nReshape to 2x6:")
print(a.reshape(2, 6))

Original:
tensor([[-1.0285,  0.3119, -0.2481,  0.4980],
        [-0.5998,  0.2868, -1.2757,  1.2483],
        [-0.2334, -1.7650, -0.2052, -0.6931]])

Flatten:
tensor([-1.0285,  0.3119, -0.2481,  0.4980, -0.5998,  0.2868, -1.2757,  1.2483,
        -0.2334, -1.7650, -0.2052, -0.6931])

Reshape to 3 x 2 x 2:
tensor([[[-1.0285,  0.3119],
         [-0.2481,  0.4980]],

        [[-0.5998,  0.2868],
         [-1.2757,  1.2483]],

        [[-0.2334, -1.7650],
         [-0.2052, -0.6931]]])

So phan tu ban dau: 12
So phan tu sau reshape: 12

Reshape to 2x6:
tensor([[-1.0285,  0.3119, -0.2481,  0.4980, -0.5998,  0.2868],
        [-1.2757,  1.2483, -0.2334, -1.7650, -0.2052, -0.6931]])


# Bài 6. Phép toán và nhân ma trận

## Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

### Yêu cầu:
#### • Phân biệt phép toán a * b với a @ b.T.
#### • Cho biết shape của kết quả a @ b.T.

In [24]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

print("\nShape của a @ b.T:")
print((a @ b.T).shape)

a:
tensor([[-1.0959, -1.4167, -1.3724],
        [-0.9265,  0.5593, -0.1985]])
b:
tensor([[-0.5097,  0.5366, -0.6574],
        [-1.2364, -2.3207, -1.6652]])

a + b:
tensor([[-1.6056, -0.8801, -2.0299],
        [-2.1628, -1.7614, -1.8637]])

a / b:
tensor([[ 2.1501, -2.6400,  2.0876],
        [ 0.7493, -0.2410,  0.1192]])

a^2:
tensor([[1.2009, 2.0070, 1.8836],
        [0.8583, 0.3128, 0.0394]])

Matrix multiplication:
tensor([[0.7006, 6.9280],
        [0.9028, 0.1781]])

Shape của a @ b.T:
torch.Size([2, 2])


# Bài 7. Các hàm thống kê trên Tensor

## Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

### Yêu cầu:
#### • Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.

In [32]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

print("\nThay dim=1:")
print(torch.mean(a, dim=1))
print(torch.std(a, dim=1))
print(torch.cumsum(a, dim=1))

tensor([[-0.5061,  0.6794, -0.2070,  1.7662],
        [ 1.4720, -0.9058, -1.5027, -1.0309],
        [ 0.5506,  0.4201,  0.6751, -1.1700]])

Mean:
tensor([ 0.5055,  0.0646, -0.3449, -0.1449])

Standard deviation:
tensor([0.9898, 0.8503, 1.0954, 1.6565])

Cumulative sum:
tensor([[-0.5061,  0.6794, -0.2070,  1.7662],
        [ 0.9658, -0.2264, -1.7097,  0.7353],
        [ 1.5165,  0.1937, -1.0347, -0.4347]])

Thay dim=1:
tensor([ 0.4331, -0.4919,  0.1189])
tensor([1.0214, 1.3342, 0.8656])
tensor([[-0.5061,  0.1733, -0.0337,  1.7324],
        [ 1.4720,  0.5662, -0.9365, -1.9674],
        [ 0.5506,  0.9707,  1.6458,  0.4758]])


# Bài 8. Autograd cơ bản

## Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

### Yêu cầu:
#### • Tính thủ công đạo hàm của y = x2 tại x = 3.6 và so sánh với x.grad.
#### • Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

In [67]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)


x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


##### Đổi hàm thành y = 3x**2 + 2x + 1 và kiểm tra gradien

In [38]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = 3*x**2 + 2*x + 1

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


# Bài 9. Gradient Descent tìm hệ số đa thức

## Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

### Yêu cầu:
#### • So sánh ba hệ số học được với [1, 2, 3].
#### • Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().

In [68]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 0.2108],
        [ 0.5792],
        [-0.0334]], requires_grad=True)
Learned coefficients:
tensor([[1.0060],
        [1.9980],
        [2.4960]], requires_grad=True)


# Bài 10. Giải hệ phương trình bằng Autograd|

## Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

### Yêu cầu:
#### • Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.
#### • Nhận xét vì sao bài toán có thể có nhiều nghiệm.

In [55]:

import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

print("\nKiem tra:")
print("A + B =", A.item() + B.item())
print("C - D =", C.item() - D.item())
print("A + C =", A.item() + C.item())
print("B - D =", B.item() - D.item())

A = tensor(4.2903, requires_grad=True)
B = tensor(4.7096, requires_grad=True)
C = tensor(3.7096, requires_grad=True)
D = tensor(2.7096, requires_grad=True)

Kiem tra:
A + B = 8.999946117401123
C - D = 1.0000114440917969
A + C = 7.999963045120239
B - D = 1.9999945163726807


# Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:


## 1.Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

In [56]:
import torch
import numpy as np
X = torch.arange(24)

print("X ban dau:")
print(X)

print("\nX reshape 4 x 6:")
print(X.reshape(4, 6))

print("\nX reshape 2 x 12:")
print(X.reshape(2, 12))

print("\nX reshape 2 x 3 x 4:")
print(X.reshape(2, 3, 4))

X ban dau:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

X reshape 4 x 6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

X reshape 2 x 12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

X reshape 2 x 3 x 4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


## 2. Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

In [59]:
import torch
import numpy as np

A = torch.rand(3, 4)
B = torch.rand(3, 4)

print("\nA:")
print(A)

print("\nB:")
print(B)

print("\nA + B:")
print(A + B)

print("\nA * B:")
print(A * B)

print("\nA / B:")
print(A / B)

print("\nTrung binh theo cot:")
print(torch.mean(A, dim=0))

print("\nDo lech chuan theo cot:")
print(torch.std(A, dim=0))



A:
tensor([[0.5800, 0.2982, 0.2673, 0.2917],
        [0.1064, 0.3413, 0.5482, 0.2878],
        [0.5187, 0.1622, 0.3596, 0.0586]])

B:
tensor([[0.4592, 0.3451, 0.4787, 0.7950],
        [0.8746, 0.2855, 0.5968, 0.3780],
        [0.8878, 0.4446, 0.4375, 0.7925]])

A + B:
tensor([[1.0392, 0.6434, 0.7460, 1.0867],
        [0.9810, 0.6268, 1.1451, 0.6658],
        [1.4065, 0.6068, 0.7971, 0.8511]])

A * B:
tensor([[0.2663, 0.1029, 0.1280, 0.2319],
        [0.0931, 0.0974, 0.3272, 0.1088],
        [0.4605, 0.0721, 0.1573, 0.0464]])

A / B:
tensor([[1.2630, 0.8641, 0.5584, 0.3670],
        [0.1217, 1.1955, 0.9186, 0.7614],
        [0.5843, 0.3648, 0.8219, 0.0739]])

Trung binh theo cot:
tensor([0.4017, 0.2672, 0.3917, 0.2127])

Do lech chuan theo cot:
tensor([0.2575, 0.0935, 0.1432, 0.1335])


## 3. Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

In [60]:
import torch
import numpy as np
x = torch.tensor(2.0, requires_grad=True)

y = 2*x**2 + 5*x + 3

y.backward()

print("\nAutograd:")
print("x =", x)
print("y =", y)
print("dy/dx =", x.grad)

# Tinh thu cong:

manual = 4*2 + 5

print("Dao ham thu cong =", manual)


Autograd:
x = tensor(2., requires_grad=True)
y = tensor(21., grad_fn=<AddBackward0>)
dy/dx = tensor(13.)
Dao ham thu cong = 13


## 4 Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [66]:
import numpy as np
import torch
polynomial = np.poly1d([2, -3, 5])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.3729],
        [0.4349],
        [1.4153]], requires_grad=True)
Learned coefficients:
tensor([[ 2.0351],
        [-2.9937],
        [ 3.6170]], requires_grad=True)
